{{- if not .Values.windmill.oauthSecretName }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-oauth-secret
type: Opaque
stringData:
  oauth.json: {{ .Values.windmill.oauthConfig }}
{{- end }}