{{- if and .Values.enterprise.createKubernetesAutoscalingRolesAndBindings .Values.enterprise.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: windmill-deployment-scaler-role
  namespace: {{ .Release.Namespace }}
rules:
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["patch","get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: windmill-deployment-scaler-rb
  namespace: {{ .Release.Namespace }}
subjects:
  - kind: ServiceAccount
    name: {{ template "windmill.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: windmill-deployment-scaler-role
  apiGroup: rbac.authorization.k8s.io
{{- end }}
{{- if .Values.windmill.operator.enabled }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Release.Name }}-windmill-operator
  labels:
    app.kubernetes.io/name: windmill-operator
    chart: {{ template "windmill.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
rules:
  - apiGroups: ["windmill.dev"]
    resources: ["windmillinstances"]
    verbs: ["get", "list", "watch", "patch"]
  - apiGroups: ["windmill.dev"]
    resources: ["windmillinstances/status"]
    verbs: ["patch", "update"]
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["create", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Release.Name }}-windmill-operator
  labels:
    app.kubernetes.io/name: windmill-operator
    chart: {{ template "windmill.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
subjects:
  - kind: ServiceAccount
    name: {{ template "windmill.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ .Release.Name }}-windmill-operator
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: windmill-operator-secrets
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: windmill-operator
    chart: {{ template "windmill.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: windmill-operator-secrets
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: windmill-operator
    chart: {{ template "windmill.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
subjects:
  - kind: ServiceAccount
    name: {{ template "windmill.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: windmill-operator-secrets
  apiGroup: rbac.authorization.k8s.io
{{- end }}
