{{- if and .Values.windmill.databaseUrlSecret .Values.windmill.databaseUrl -}}
apiVersion: v1
kind: Secret
metadata:
  name: windmill-database
  labels:
    app: windmill-database
    app.kubernetes.io/name: windmill-database
    chart: {{ template "windmill.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  url: {{ .Values.windmill.databaseUrl | b64enc | quote }}
{{- end -}}
